 language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/install_dependency.sh; fi
script:
- if [ $TRAVIS_OS_NAME == linux ]; then mkdir ../build && cd ../build fi
- if [ $TRAVIS_OS_NAME == linux ]; then cmake ../CapitalWorld/CMakeLists.txt && make; fi
after_success:
- if [ $TRAVIS_OS_NAME == linux ]; then make package; fi
#- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then ./scripts/deploy.sh release github website triggers; fi
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
deploy:
  provider: releases
  api_key: "9aab48af678733c4b76f48d165a20e45426c2e96"
  file: "CapitalWorld-0.1-Linux.deb"
  skip_cleanup: true
  on:
    tags: true
addons:
  apt:
    packages:
      - cmake-data
      - cmake
