language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/install_dependency.sh; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    pwd;
    mkdir build; 
    pwd;
    cmake -S `pwd` -B `pwd`/build;
    cmake --build `pwd`/build --config release --target CapitalWorld ;
    fi
after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then cd `pwd`/build && make package; fi
#- if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then ./scripts/deploy.sh release github website triggers; fi
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: false
deploy:
  provider: releases
  file: "CapitalWorld-0.1-Linux.deb"
  skip_cleanup: true
  on:
    tags: true
addons:
  apt:
    packages:
      - cmake-data
      - cmake