name: CI
on: [push,pull_request]
jobs:
  job:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows (x64)
            os: windows-latest
            triplet: x64-windows
            experimental: false
          - name: Windows (x86)
            os: windows-latest
            triplet: x86-windows
            experimental: false
          - name: Ubuntu (GCC)
            os: ubuntu-latest
            triplet: x64-linux
            cc: gcc
            cxx: g++
            experimental: false
          - name: Ubuntu (Clang)
            os: ubuntu-latest
            triplet: x64-linux
            cc: clang
            cxx: clang++
            experimental: false

    env:
      # Indicates the CMake build directory where project files and binaries are being produced.
      CMAKE_BUILD_DIR: ${{ github.workspace }}/build/
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      #VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Linux dependencies
        run: |
          sudo apt install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-gfx-dev libsdl2-mixer-dev libz-dev
        if: matrix.os == 'ubuntu-latest'

      - name: Show content of workspace after cache has been restored
        run: find $RUNNER_WORKSPACE
        shell: bash

      # On Windows runners, let's ensure to have the Developer Command Prompt environment setup correctly. As used here the Developer Command Prompt created is targeting x64 and using the default the Windows SDK.
      - uses: ilammy/msvc-dev-cmd@v1

      # Run CMake to generate Ninja project files, using the vcpkg's toolchain file to resolve and install the dependencies as specified in vcpkg.json.
      - name: Install dependencies and generate project files
        run: |
          cmake -B "${{ env.CMAKE_BUILD_DIR }}" 
      # Build the whole project with Ninja (which is spawn by CMake).
      - name: Build
        run: |
          cmake --build "${{ env.CMAKE_BUILD_DIR }}" --target CapitalWorld
      - name: Show content of workspace at its completion
        run: find $RUNNER_WORKSPACE
        shell: bash
